"""Position descriptions for the oracle, as FEN.

**Why FEN rather than an invented format.** The oracle's honest scope is move
generation (migration-plan §0), and FEN describes exactly the state the old
engine's move generator reads: placement, side to move, castling rights, and the
en-passant target. It is also reviewable — a failing position pastes straight
into any chess GUI — and it unlocks the published perft suite as external ground
truth, which an invented format would not.

**Why FEN is sufficient here, verified rather than assumed.** FEN cannot express
`has_moved`, and a reader would reasonably worry that this loses information.
It does not, for this engine: `has_moved` is written in `pieces/base.py:24` and
**never read during move generation**. The pawn double-step gates on *rank*
(`standard.py:41`) and castling gates on `current_castle_rights`
(`standard.py:190`).

That changes for the new engine, deliberately — the spec gates the double-step on
`has_moved` instead (content-schemas finding 3), because rank-gating hardcodes a
board size that UC12 forbids. For positions reached by **legal play** the two
rules agree, because pawns never move backwards: a white pawn on rank 2 has
provably never moved. They diverge only via colour conversion
(`mat_quyen_cong_dan`), which is exactly the case C3 flagged. **This is why
random positions must be generated by random legal play rather than by scattering
pieces** — arbitrary placement would manufacture a divergence that no real game
can reach, and the oracle would report a bug that isn't one.

Fused pieces (`A`/`C`/`W`/`I`) extend FEN with the engine's own codes, following
FEN's case convention for colour.
"""

from src.constants import (
    ARCHBISHOP_CODE,
    BISHOP_CODE,
    BLACK,
    BOARD_COLS,
    BOARD_ROWS,
    CHANCELLOR_CODE,
    INQUISITOR_CODE,
    KING_CODE,
    KNIGHT_CODE,
    PAWN_CODE,
    QUEEN_CODE,
    ROOK_CODE,
    WARDEN_CODE,
    WHITE,
)

# FEN's own geometry, which is 8x8 by definition — not the engine's board size.
# The two are equal today and must not be conflated: when UC12's total conversion
# makes BOARD_ROWS mean something else, this stays 8 and FEN stops being an
# adequate description. That is a signal to change the format, not this constant.
FEN_RANKS = 8
from src.game.board import GameState
from src.game.castling import CastleRights, copy_castle_rights
from src.pieces import create_piece

STARTING_FEN = "rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1"

# FEN letter (upper) -> engine piece code. Note the pawn: the engine's code is
# lowercase "p" for BOTH colours, while FEN uses case to mean colour. Colour is
# carried separately by the engine, so the two conventions must not be conflated.
FEN_TO_CODE = {
    "P": PAWN_CODE,
    "N": KNIGHT_CODE,
    "B": BISHOP_CODE,
    "R": ROOK_CODE,
    "Q": QUEEN_CODE,
    "K": KING_CODE,
    # Fused pieces — a FEN extension, using the engine's codes.
    "A": ARCHBISHOP_CODE,
    "C": CHANCELLOR_CODE,
    "W": WARDEN_CODE,
    "I": INQUISITOR_CODE,
}
CODE_TO_FEN = {code: letter for letter, code in FEN_TO_CODE.items()}


def square_to_rc(square):
    """'e4' -> (row, col). Grid row 0 is rank 8, matching Move.ranks_to_rows."""
    file_char, rank_char = square[0], square[1]
    return FEN_RANKS - int(rank_char), ord(file_char) - ord("a")


def rc_to_square(row, col):
    """(row, col) -> 'e4'."""
    return chr(ord("a") + col) + str(FEN_RANKS - row)


def game_state_from_fen(fen):
    """Build a GameState standing at `fen`.

    Constructs a normal GameState (which sets up the classic position), then
    replaces the grid wholesale. Going through GameState() rather than
    hand-building keeps every collaborator it wires up — trackers, managers,
    post-move systems — exactly as the real game has them.
    """
    placement, side, castling, enpassant = fen.split()[:4]

    state = GameState()
    state.board.grid = [[None for _ in range(BOARD_COLS)] for _ in range(BOARD_ROWS)]

    for row, rank in enumerate(placement.split("/")):
        col = 0
        for char in rank:
            if char.isdigit():
                col += int(char)
                continue
            colour = WHITE if char.isupper() else BLACK
            piece = create_piece(FEN_TO_CODE[char.upper()], colour, (row, col))
            state.board.grid[row][col] = piece
            col += 1

    state.white_to_move = side == "w"
    state.current_castle_rights = CastleRights(
        wks="K" in castling,
        bks="k" in castling,
        wqs="Q" in castling,
        bqs="q" in castling,
    )
    state.castle_rights_log = [copy_castle_rights(state.current_castle_rights)]
    state.enpassant_possible = () if enpassant == "-" else square_to_rc(enpassant)
    state.move_log = []

    _locate_kings(state, fen)
    return state


def _locate_kings(state, fen):
    """Point the cached king positions at the kings this FEN actually has.

    **Both kings are required, and a missing one is an error rather than a
    default.** `GameState.__init__` pre-seeds `white_king_pos = (7, 4)` for the
    classic setup. A FEN without a white king would silently keep that value,
    `in_check()` would probe a square holding no king, and king-safety filtering
    would quietly return a wrong move set — with no exception and nothing in the
    output looking wrong.

    That matters most in exactly the situation someone reaches for a fragment
    position: debugging a divergence by hand. `CLAUDE.md` is explicit — fail
    loud, never silently skip malformed content — and an oracle that lies under
    the debugger is worse than no oracle.
    """
    found = {}
    for row in range(BOARD_ROWS):
        for col in range(BOARD_COLS):
            piece = state.board.grid[row][col]
            if piece is not None and piece.get_piece_code() == KING_CODE:
                found[piece.color] = (row, col)

    missing = [name for colour, name in ((WHITE, "white"), (BLACK, "black")) if colour not in found]
    if missing:
        raise ValueError(
            f"FEN has no {' or '.join(missing)} king: {fen!r}\n"
            f"  Both kings are required. Without one, GameState's default king "
            f"position survives and every move set this position produces is "
            f"silently wrong."
        )

    state.white_king_pos = found[WHITE]
    state.black_king_pos = found[BLACK]


def fen_from_game_state(state):
    """Serialise a GameState back to FEN.

    The halfmove and fullmove counters are emitted as `0 1`: the engine does not
    track them, and they do not affect move generation. Anything that comes to
    depend on them needs a real field, not a guess from this function.
    """
    ranks = []
    for row in range(BOARD_ROWS):
        rank, empty = "", 0
        for col in range(BOARD_COLS):
            piece = state.board.grid[row][col]
            if piece is None:
                empty += 1
                continue
            if empty:
                rank += str(empty)
                empty = 0
            letter = CODE_TO_FEN[piece.get_piece_code()]
            rank += letter if piece.color == WHITE else letter.lower()
        if empty:
            rank += str(empty)
        ranks.append(rank)

    rights = state.current_castle_rights
    castling = "".join(
        flag
        for flag, allowed in (
            ("K", rights.wks), ("Q", rights.wqs),
            ("k", rights.bks), ("q", rights.bqs),
        )
        if allowed
    )

    enpassant = rc_to_square(*state.enpassant_possible) if state.enpassant_possible else "-"

    return (
        f"{'/'.join(ranks)} "
        f"{'w' if state.white_to_move else 'b'} "
        f"{castling or '-'} "
        f"{enpassant} 0 1"
    )
